### ISSUE TITLE
搜尋成員會有白邊

### ISSUE THREAD

**Issue by sdaru18** [trello123/Disboard-demo-#187]
如圖 右邊有多白邊
<img width="570" alt="截圖 2023-05-26 上午12 07 57" src="https://github.com/trello123/Disboard-demo-/assets/130148376/dfb5fac6-278e-4660-ad89-55d1cdd1c65f">

**Comment by gh20000528** [comment]
我的沒有白邊誒

**Comment by sdaru18** [comment]
那請其他人試一下好了 可能是我瀏覽器問題
