### ISSUE TITLE
搜尋成員打mail會出現＠後面全部有mail的

### ISSUE THREAD

**Issue by sdaru18** [trello123/Disboard-demo-#189]
我記得只能搜＠前面的英文跟名稱而已

<img width="584" alt="截圖 2023-05-26 上午12 33 45" src="https://github.com/trello123/Disboard-demo-/assets/130148376/6579354e-67c2-45c9-86e7-fbd39e82bf02">

**Comment by karokwbh** [comment]
只會有五筆而已

**Comment by sdaru18** [comment]
我以為是只能搜@前面的字而已
我誤會
